<h1 class="uk-text-danger">Mes articles</h1>

<div class="uk-margin-small uk-overflow-auto uk-height-medium">
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <h3 class="uk-card-title uk-text-primary">Liste Articles Enregistrés</h3>
        </div>
        <div class="uk-card-body" id="liste">
            <!--p class="uk-alert uk-alert-warning" uk-alert>Vous n'avez pas d'article enregistré.</p-->
            <!--<table class="uk-table uk-table-expand uk-table-divider uk-table-small">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Catégorie</th>
                        <th>Titre</th>
                        <th>Aperçu</th>
                        <th>Date d'édition</th>
                        <th>Auteur</th>
                        <th>Etat</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Sport</td>
                        <td><a href="">Mon premier article</a></td>
                        <td>
                            Ceci est mon premier article
                        </td>
                        <td>25-03-2019</td>
                        <td>Toto</td>
                        <td>Publié</td>
                        <td>
                            <span class="uk-button uk-button-small uk-button-link uk-text-success">1220 Vue(s)</span>
                            <span class="uk-button uk-button-small uk-button-link uk-text-warning">220 Commentaire(s)</span>
                        </td>
                        <td>
                            <a href="" class="uk-text-primary" uk-icon="icon: pencil" uk-tooltip="title: Modifier l'article"></a>
                            <a href="" class="uk-text-danger" uk-icon="icon: trash" uk-tooltip="title: Supprimer l'article"></a>
                        </td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Cinéma</td>
                        <td><a href="">Mon deuxième article</a></td>
                        <td>
                            Ceci est mon deuxième article
                        </td>
                        <td>26-03-2019</td>
                        <td>Tata</td>
                        <td>Publié</td>
                        <td>
                            <span class="uk-button uk-button-small uk-button-link uk-text-success">1220 Vue(s)</span>
                            <span class="uk-button uk-button-small uk-button-link uk-text-warning">220 Commentaire(s)</span>
                        </td>
                        <td>
                            <a href="" class="uk-text-primary" uk-icon="icon: pencil" uk-tooltip="title: Modifier l'article"></a>
                            <a href="" class="uk-text-danger" uk-icon="icon: trash" uk-tooltip="title: Supprimer l'article"></a>
                        </td>
                    </tr>
                </tbody>
            </table>-->
        </div>
    </div>
</div>
<div>
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <h3 class="uk-card-title uk-text-primary">Nouveau article</h3>
        </div>
        <div class="uk-card-body">
            <form action="" id="frmAddArticle">
                <div>
                    <div class="uk-grid uk-grid-small uk-child-width-expand\@s" uk-grid>
                        <div class="uk-width-2-3">
                            <div class="">
                                <label for="" class="uk-form-label">Titre*</label>
                                <input type="text" id="titre" class="uk-input" placeholder="Entrez le titre de l'article">
                            </div>
                        </div>
                        <div class="uk-width-1-3">
                            <div class="">
                                <label for="" class="uk-form-label">Publication</label>
                                <select name="" id="etat" class="uk-select uk-form-controls">
                                    <option value="publié">Publié</option>
                                    <option value="non publié">Non publié</option>
                                </select>
                            </div>
                        </div>
                        <div class="uk-width-1-1">
                            <textarea name="contenu" id="contenu" rows="20" class="uk-textarea"></textarea>
                        </div>
                    </div>
                </div>
                <div class="uk-margin-top uk-text-right">
                    <button class="uk-button uk-button-primary uk-button-small" type="submit">Enregistrer</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'contenu' );
</script>

<script src="js/articles.js"></script>