<h1 class="uk-text-danger">Mes articles</h1>

<div>
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <h3 class="uk-card-title uk-text-primary">Modification article</h3>
        </div>
        <div class="uk-card-body">
            <form action="" method="post" id="frmAddArticle">
                <div>
                    <div class="uk-grid uk-grid-small uk-child-width-expand\@s" uk-grid>
                        <div class="uk-width-2-3">
                            <div class="">
                                <label for="" class="uk-form-label">Titre*</label>
                                <input type="text" id="titre" class="uk-input" placeholder="Entrez le titre de l'article">
                            </div>
                        </div>
                        <div class="uk-width-1-3">
                            <div class="">
                                <label for="" class="uk-form-label">Publication</label>
                                <select name="" id="etat" class="uk-select uk-form-controls">
                                    <option value="publié">Publié</option>
                                    <option value="non publié">Non publié</option>
                                </select>
                            </div>
                        </div>
                        <div class="uk-width-1-1">
                            <textarea name="contenu" id="contenu" rows="20" class="uk-textarea"></textarea>
                        </div>
                    </div>
                </div>
                <div class="uk-margin-top uk-text-right">
                    <button class="uk-button uk-button-primary uk-button-small" type="submit">Enregistrer</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'contenu' );
</script>

<script src="js/articles.js"></script>