<?php
$mngPage = new \Libs\panel\MngArticles();
if (count($this->getParams()) == 1){
    $id_article = (int) $this->getParams()[1];
    if ($id_article > 0){
        $article = $mngPage->getArticle($id_article);
    }
}
$error = [];
if (isset($_POST) && !empty($_POST)){
    $contenu = $_POST["contenu"];
    $etat = $_POST["etat"];
    $titre = $_POST["titre"];
    if ($contenu == ""){
        array_push($error, "Veuillez saisir le contenu de l'article");
    }
    if ($titre == ""){
        array_push($error, "Veuillez saisir le titre la page");
    }


    if (empty($error)){
        $page_data = new \Libs\panel\Article($titre, $contenu, $etat);
        if ($mngPage->updateArticle($page_data, $id_article)){
            ?>
            <script>
                $(function () {
                    $("#frmAddArticle").hide()();
                });
                UIkit.notification({
                    message: '<b>Succès !</b> L'article a été modifiée',
                    status: 'primary',
                    pos: 'top-right',
                    timeout: 3000
                });
                window.setTimeout(function () {
                    window.location.href = 'articles';
                    //$("#toBack").click();
                }, 3000);

            </script>
            <?php
        }
    }

}
?>
    <h1 class="uk-text-danger">Mes articles</h1>
<?php if (isset($article) && $article): ?>
    <div>
        <div class="uk-card uk-card-default">
            <div class="uk-card-header">
                <h3 class="uk-card-title">Modification article</h3>
            </div>
            <?php if (!empty($error)): ?>
                <div class="uk-alert uk-alert-warning uk-padding-small uk-margin-medium-left uk-margin-medium-right" uk-alert>
                    <h4 class="uk-margin-remove-bottom">Echèc de validation</h4>
                    <hr class="uk-margin-remove">
                    <ul>
                        <?php for ($i = 0; $i < count($error); $i++): ?>
                            <li><?= $error[$i]; ?></li>
                        <?php endfor; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <div class="uk-card-body">
                <form action="" method="post" id="frmAddArticle">
                    <div>
                        <div class="uk-grid uk-grid-small uk-child-width-expand\@s" uk-grid>
                            <div class="uk-width-2-3">
                                <div class="">
                                    <label for="titre" class="uk-form-label">Titre*</label>
                                    <input type="text" name="titre" id="titre" class="uk-input" placeholder="Entrez le titre de l'article" value="<?= $article->titre; ?>">
                                </div>
                            </div>
                            <div class="uk-width-1-3">
                                <div class="">
                                    <label for="etat" class="uk-form-label">Publication</label>
                                    <select name="etat" id="etat" class="uk-select uk-form-controls">
                                        <option value="publié" <?= $article->etat == 'publié' ? 'selected' : ''; ?>>Publié</option>
                                        <option value="non publié" <?= $article->etat == 'non publié' ? 'selected' : ''; ?>>Non publié</option>
                                    </select>
                                </div>
                            </div>
                            <div class="uk-width-1-1">
                                <textarea name="contenu" id="contenu" rows="20" class="uk-textarea">
                                    <?= $article->contenu; ?>
                                </textarea>
                            </div>
                        </div>
                    </div>
                    <div class="uk-margin-top uk-text-right">
                        <button class="uk-button uk-button-primary uk-button-small" type="submit">Enregistrer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'contenu', {
            filebrowserUploadUrl: "upload.php"
        });
    </script>

    <!--script src="js/page-article.js"></script-->
<?php else: ?>
    <div class="uk-alert uk-alert-danger" uk-alert>
        <h1>Erreur ! ------------------------------------------------------------------------------></h1>
        <p class="uk-text-muted uk-text-large">
            Impossible d'afficher cet article
        </p>
    </div>
<?php endif; ?>