<h1 class="uk-text-danger">Flash Info</h1>

<div class="uk-margin-small uk-overflow-auto uk-height-medium">
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <h3 class="uk-card-title">Liste des infos Enregistrés</h3>
        </div>
        <div class="uk-card-body">
            <p class="uk-alert uk-alert-warning" uk-alert>Vous n'avez pas d'article enregistré.</p>
            <!--<table class="uk-table uk-table-expand uk-table-divider uk-table-small">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Catégorie</th>
                        <th>Titre</th>
                        <th>Aperçu</th>
                        <th>Date d'édition</th>
                        <th>Auteur</th>
                        <th>Etat</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Sport</td>
                        <td><a href="">Mon premier article</a></td>
                        <td>
                            Ceci est mon premier article
                        </td>
                        <td>25-03-2019</td>
                        <td>Toto</td>
                        <td>Publié</td>
                        <td>
                            <span class="uk-button uk-button-small uk-button-link uk-text-success">1220 Vue(s)</span>
                            <span class="uk-button uk-button-small uk-button-link uk-text-warning">220 Commentaire(s)</span>
                        </td>
                        <td>
                            <a href="" class="uk-text-primary" uk-icon="icon: pencil" uk-tooltip="title: Modifier l'article"></a>
                            <a href="" class="uk-text-danger" uk-icon="icon: trash" uk-tooltip="title: Supprimer l'article"></a>
                        </td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>Cinéma</td>
                        <td><a href="">Mon deuxième article</a></td>
                        <td>
                            Ceci est mon deuxième article
                        </td>
                        <td>26-03-2019</td>
                        <td>Tata</td>
                        <td>Publié</td>
                        <td>
                            <span class="uk-button uk-button-small uk-button-link uk-text-success">1220 Vue(s)</span>
                            <span class="uk-button uk-button-small uk-button-link uk-text-warning">220 Commentaire(s)</span>
                        </td>
                        <td>
                            <a href="" class="uk-text-primary" uk-icon="icon: pencil" uk-tooltip="title: Modifier l'article"></a>
                            <a href="" class="uk-text-danger" uk-icon="icon: trash" uk-tooltip="title: Supprimer l'article"></a>
                        </td>
                    </tr>
                </tbody>
            </table>-->
        </div>
    </div>
</div>
<div>
    <div class="uk-card uk-card-default">
        <div class="uk-card-header">
            <h3 class="uk-card-title">Ajouter un article</h3>
        </div>
        <div class="uk-card-body">
            <form action="">
                <div class="uk-grid uk-grid-small uk-child-width-expand\@s" uk-grid>
                    <div class="uk-width-4-5">
                        <input type="text" class="uk-input" placeholder="Information">
                    </div>
                    <div class="uk-width-1-5">
                        <button class="uk-button uk-button-primary">Enregistrer</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>