<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Application</title>
    <link rel="stylesheet" href="f/ui/css/uikit.min.css">

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="f/ui/js/uikit.min.js" charset="utf-8"></script>
    <script src="f/ui/js/uikit-icons.min.js" charset="utf-8"></script>

    <script src="f/ckeditor/ckeditor.js" charset="utf-8"></script>
</head>
<body>
    <!-- Page Content -->
    <?= $output; ?>
      <!-- End page content -->
</body>
</html>