
<section class="uk-box-shadow-small">
	<div class="uk-padding-small">
   <!--h1>Contact</h1-->
    <div class="uk-child-width-expand@s" uk-grid>
        <div class="uk-width-1-3">
            <!--div class="uk-padding-small">
            <h3>Heading</h3>
            <div>
                <div>La Direction des Bourses est situe&eacute; au Plateau, Av&eacute;nue Nogu&egrave;s, Immeuble Nogu&egrave;s, 1er &eacute;tageAbidjanCOTE D&#39;IVOIRECode postalCOTE D&#39;IVOIRE</div>

                    <p><img alt="Téléphone: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_tel.png" /> T&eacute;l&eacute;phone</p>

                    <p><img alt="Fax: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_fax.png" /> 20 32 75 53</p>

                    <p><img alt="Mobile: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_mobile.png"/> 20 32 32 50</p>
                </div>
            </div-->
            <h3>Contact</h3>
            <div>
                <div class="uk-text-small uk-text-justify"><span uk-icon="icon: location"></span> La Direction des Bourses est situe&eacute; au Plateau, Av&eacute;nue Nogu&egrave;s, Immeuble Nogu&egrave;s, 1er &eacute;tage Abidjan COTE D&#39;IVOIRE - Code postal COTE D&#39;IVOIRE</div>

                <p><span uk-icon="icon: receiver"></span> 20 32 75 53</p>

                <p><span uk-icon="icon: phone"></span> 20 32 75 50</p>

                <p><span uk-icon="icon: mail"></span> contact@mail.com</p>
                <!--p><img alt="Téléphone: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_tel.png" /> Téléphone</p>

                <p><img alt="Fax: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_fax.png" /> 20 32 75 53</p>

                <p><img alt="Mobile: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_mobile.png"/> 20 32 32 50</p-->
            </div>
        </div>
        <div class="uk-width-2-3">
            <form>
                <fieldset class="uk-fieldset uk-padding-remove">
                    <legend class="uk-legend">Formulaire de contact</legend>

                    <div class="uk-margin">
                        <input class="uk-input" type="text" placeholder=" Votre Nom*">
                    </div>

                    <div class="uk-margin">
                        <input class="uk-input" type="text" placeholder=" Votre adresse E-mail*">
                    </div>

                    <div class="uk-margin">
                        <input class="uk-input" type="text" placeholder=" Saisir l'Objet*">
                    </div>

                    <div class="uk-margin">
                        <textarea class="uk-textarea" rows="5" placeholder="Votre Message*"></textarea>
                    </div>

                    <button class="uk-button uk-button-default uk-width-1-1 uk-margin-small-bottom">Envoyer</button>

                </fieldset>
            </form>
        </div>
    </div>

    <div class="uk-padding-small">
        <div class="uk-child-width uk-text-center" uk-grid>
            <div>
                <div class="uk-card uk-card-default uk-card-body">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3972.646191677293!2d-4.018314885235119!3d5.317763596142353!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfc1ebc78396443d%3A0x7e1964d5cbb24a8b!2sAvenue+Nogu%C3%A8s%2C+Abidjan!5e0!3m2!1sfr!2sci!4v1553751823698!5m2!1sfr!2sci" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>

</section>







