<div class="uk-section uk-light uk-section-small" style="background: green">
    <div class="uk-container">
        <div class="uk-grid-match uk-child-width-1-4@m uk-grid-divider" uk-grid>
            <div>
                <h4>LIENS</h4>
                <hr class="uk-margin-remove" style="background: orange">
                <ul>
                    <li class="uk-active"><a href="<?= URL; ?>">Accueil</a></li>
                    <li><a href="<?= URL.'historique'; ?>">Historique</a></li>
                    <li><a href="<?= URL.'presentation'; ?>">Présentation</a></li>
                    <li><a href="<?= URL.'organisation'; ?>">Organisation</a></li>
                    <li><a href="<?= URL.'organigramme'; ?>">Organigramme</a></li>
                </ul>
            </div>
            <div>
                <h4>LIENS</h4>
                <hr class="uk-margin-remove" style="background: orange">
                <ul>
                    <li><a href="<?= URL.'missions'; ?>">Missions</a></li>
                    <li><a href="<?= URL.'partenaires'; ?>">Partenaires</a></li>
                    <li><a href="<?= URL.'annuaire'; ?>">Annuaire</a></li>
                    <li><a href="<?= URL.'actualites'; ?>">Actualités</a></li>
                    <li><a href="<?= URL.'contact'; ?>">Contact</a></li>
                </ul>
            </div>
            <div>
                <h4>LIENS</h4>
                <hr class="uk-margin-remove" style="background: orange">
                <ul>
                    <li><a href="<?= URL.'communiques'; ?>">Communiqués</a></li>
                    <li><a href="<?= URL.'documentation'; ?>">Documentation</a></li>
                    <li><a href="<?= URL.'informations'; ?>">Informations Utiles</a></li>
                    <li><a href="<?= URL.'faq'; ?>">FAQ</a></li>
                    <li><a href="<?= URL.'lien_utile'; ?>">Liens Utiles</a></li>
                </ul>
            </div>
            <div>
                <h4>CONTACT</h4>
                <div>
                    <div class="uk-text-small uk-text-justify"><span uk-icon="icon: location"></span> La Direction des Bourses est situe&eacute; au Plateau, Av&eacute;nue Nogu&egrave;s, Immeuble Nogu&egrave;s, 1er &eacute;tage Abidjan COTE D&#39;IVOIRE - Code postal COTE D&#39;IVOIRE</div>

                    <p><span uk-icon="icon: receiver"></span> 20 32 75 53</p>

                    <p><span uk-icon="icon: phone"></span> 20 32 75 50</p>

                    <p><span uk-icon="icon: mail"></span> contact@mail.com</p>
                    <!--p><img alt="Téléphone: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_tel.png" /> Téléphone</p>

                    <p><img alt="Fax: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_fax.png" /> 20 32 75 53</p>

                    <p><img alt="Mobile: " src="http://www.bourses.enseignement.gouv.ci/media/contacts/images/con_mobile.png"/> 20 32 32 50</p-->
                </div>
            </div>
        </div>
        <hr class="uk-divider-icon">
        <div class="uk-width-1-1 uk-padding-small uk-text-center" style="background: orange">
            Copyright &copy; Ministère de l'Enseignement Supérieur et de la Recherche Scientifique: Direction Des Bourses | Conception &amp; Hébergement:
            <a href="www.sndi.ci">SNDI</a>
        </div>
    </div>
</div>