<?php
$mngPage = new \Libs\panel\MngPageArticle();
$page = $mngPage->getPargeArticleByPage("motdudirecteur");
?>
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Direction Des Bourses</title>
    <base href="<?= URL; ?>">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="f/ui/css/uikit.min.css">

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="f/ui/js/uikit.min.js" charset="utf-8"></script>
    <script src="f/ui/js/uikit-icons.min.js" charset="utf-8"></script>

    <!--script src="f/ckeditor/ckeditor.js" charset="utf-8"></script-->
</head>
<body>
<div id="navSmallDivice" uk-offcanvas="overlay: true">
    <div class="uk-offcanvas-bar">

        <ul class="uk-nav uk-nav-primary"">
            <li class=""><a href="<?= URL; ?>">Accueil</a></li>
            <li><a href="<?= URL.'historique'; ?>">Historique</a></li>
            <li><a href="<?= URL.'presentation'; ?>">Présentation</a></li>
            <li><a href="<?= URL.'organisation'; ?>">Organisation</a></li>
            <li><a href="<?= URL.'organigramme'; ?>">Organigramme</a></li>
            <li><a href="<?= URL.'missions'; ?>">Missions</a></li>
            <li><a href="<?= URL.'partenaires'; ?>">Partenaires</a></li>
            <li><a href="<?= URL.'annuaire'; ?>">Annuaire</a></li>
            <li><a href="<?= URL.'actualites'; ?>">Actualités</a></li>
            <li><a href="<?= URL.'contact'; ?>">Contact</a></li>
        </ul>

    </div>
</div>
    <div class="">
      <?php //include_once 'tpl/header.phtml'; ?>
        <!-- Header -->
        <div class="uk-container uk-container-expand uk-container-small uk-background-cover uk-visible@m" id="header" style="background-image: url(img/ban.jpg);">
            <div class="uk-container uk-width-1-1@s">
                <div id="top_Banner" class="uk-height-small uk-width-1-1@s">
                </div>
                <nav class="uk-navbar-container uk-margin-remove-bottom uk-padding-remove uk-navbar-transparent" uk-navbar="mode: click" style="background: #fff;text-align: center;">
                    <div class="uk-navbar">

                        <ul class="uk-navbar-nav" style="padding: 0px !important;">
                            <li class="uk-active"><a href="<?= URL; ?>">Accueil</a></li>
                            <li><a href="<?= URL.'historique'; ?>">Historique</a></li>
                            <li><a href="<?= URL.'presentation'; ?>">Présentation</a></li>
                            <li><a href="<?= URL.'organisation'; ?>">Organisation</a></li>
                            <li><a href="<?= URL.'organigramme'; ?>">Organigramme</a></li>
                            <li><a href="<?= URL.'missions'; ?>">Missions</a></li>
                            <li><a href="<?= URL.'partenaires'; ?>">Partenaires</a></li>
                            <li><a href="<?= URL.'annuaire'; ?>">Annuaire</a></li>
                            <li><a href="<?= URL.'actualites'; ?>">Actualités</a></li>
                            <li><a href="<?= URL.'contact'; ?>">Contact</a></li>
                        </ul>

                    </div>
                </nav>
            </div>
        </div>
        <!-- End Header-->
        <div class="uk-container">
            <div class="uk-alert uk-alert-warning uk-padding-remove uk-margin-remove uk-visible@m">
                <b>Flash Info</b>
                <hr class="uk-margin-remove">
                <marquee behavior="" direction="">SITE OFFICIEL DE LA DIRECTION DES BOURSE</marquee>
            </div>

            <div class="uk-hidden@m">
                <a href="#" class="" type="button" uk-toggle="target: #navSmallDivice" uk-icon="icon: table"></a>
                <hr class="uk-divider-icon uk-margin-remove">
            </div>

            <div class="uk-position-relative uk-width-1-1@s">
                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1" uk-slideshow="animation: scale; autoplay: true; max-height:250; ratio: 7:3">

                    <ul class="uk-slideshow-items uk-width-1-1@s">
                        <li>
                            <!--img src="img/slid0.jpeg" height="200" alt="" uk-cover-->
                            <img src="img/dir bourse.jpg" height="200" alt="" uk-cover>
                        </li>
                        <li>
                            <!--img src="img/slid0.jpeg" height="200" alt="" uk-cover-->
                            <img src="img/bourse ivoire.jpg" height="200" alt="" uk-cover>
                        </li>
                        <li>
                            <!--img src="img/slid0.jpeg" height="200" alt="" uk-cover-->
                            <img src="img/bourse etranger.jpg" height="200" alt="" uk-cover>
                        </li>
                    </ul>

                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>

                </div>
            </div>
            <div class="uk-alert uk-alert-warning uk-padding-remove uk-margin-remove uk-hidden@m">
                <b>Flash Info</b>
                <hr class="uk-margin-remove">
                <marquee behavior="" direction="">SITE OFFICIEL DE LA DIRECTION DES BOURSE</marquee>
            </div>
            <hr>
            <div>
                <div class="uk-grid uk-grid-small uk-grid-default uk-child-width-expand@s" uk-grid>
                    <div class="uk-width-1-5@l uk-width-1-1@s uk-visible@m" id="leftSide">
                        <?php if ($page && $page->etat=='publié'): ?>
                            <div class="uk-card uk-card-small">
                                <div class="uk-card-media-top">
                                    <img src="http://ensabidjan.ci/images/dg.jpg" alt="Photo du Directeur">
                                </div>
                                <div class="uk-card-body uk-padding-remove" style="padding: 5px !important;">
                                    <h3 class="uk-card-title"><u>MOT DU DIRECTEUR</u></h3>
                                    <p><?= substr($page->contenu, 0, 100); ?></p>
                                </div>
                                <div class="uk-card-footer">
                                    <a href="<?= URL.'directeur'; ?>" class="uk-button uk-button-default">Lire la suite</a>
                                </div>
                            </div>
                            <hr class="uk-divider-icon">
                        <?php else: ?>
                            <section class="uk-box-shadow-small">
                                <p class="uk-alert uk-alert-warning" uk-alert>
                                    Section en construction
                                </p>
                            </section>
                        <?php endif; ?>
                    </div>
                    <div class="uk-width-1-1@s uk-width-3-5@l">
                        <!-- Page Content -->
                        <?= $output; ?>
                        <!-- End page content -->
                    </div>
                    <div class="uk-width-1-5@l uk-width-1-1@s uk-hidden@m" id="leftSide">
                        <?php if ($page && $page->etat=='publié'): ?>
                            <div class="uk-card uk-card-small">
                                <div class="uk-card-media-top">
                                    <img src="http://ensabidjan.ci/images/dg.jpg" alt="Photo du Directeur">
                                </div>
                                <div class="uk-card-body uk-padding-remove" style="padding: 5px !important;">
                                    <h3 class="uk-card-title"><u>MOT DU DIRECTEUR</u></h3>
                                    <p><?= substr($page->contenu, 0, 100); ?></p>
                                </div>
                                <div class="uk-card-footer">
                                    <a href="<?= URL.'directeur'; ?>" class="uk-button uk-button-default">Lire la suite</a>
                                </div>
                            </div>
                            <hr>
                        <?php else: ?>
                            <section class="uk-box-shadow-small">
                                <p class="uk-alert uk-alert-warning" uk-alert>
                                    Section en construction
                                </p>
                            </section>
                        <?php endif; ?>
                    </div>
                    <div class="uk-width-1-1@s uk-width-1-5@l" id="rightSide">
                        <div>
                            <ul class="uk-nav uk-nav-default">
                                <li class="uk-nav-header">ESPACE ETUDIANT</li>
                                <li class="uk-nav-divider"></li>
                                <li><a href="<?= URL.'guide_etudiant_boursier'; ?>">Guide de l'étudiant boursier</a></li>
                                <li><a href="<?= URL.'droit_et_recours'; ?>">Droit et recours</a></li>
                            </ul>
                        </div>
                        <hr class="uk-divider-icon">
                        <div>
                            <ul class="uk-nav uk-nav-default">
                                <li class="uk-nav-header">BOURSE D'ETUDE EN CÔTE D'IVOIRE</li>
                                <li class="uk-nav-divider"></li>
                                <li><a href="<?= URL.'ci_appel_candidature'; ?>">Appel à canditdature</a></li>
                                <li><a href="<?= URL.'ci_condition_eligibilite'; ?>">Condition d'éligibilité</a></li>
                            </ul>
                        </div>
                        <hr class="uk-divider-icon">
                        <div>
                            <ul class="uk-nav uk-nav-default">
                                <li class="uk-nav-header">BOURSE D'ETUDE HORS CÔTE D'IVOIRE</li>
                                <li class="uk-nav-divider"></li>
                                <li><a href="<?= URL.'et_appel_candidature'; ?>">Appel à canditdature</a></li>
                                <li><a href="<?= URL.'et_condition_eligibilite'; ?>">Condition d'éligibilité</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>


      <?php include_once 'tpl/footer.phtml' ?>
    </div>
</body>
</html>
